### ISSUE TITLE
H5 页面横向滚动条隐藏

### ISSUE THREAD

**Issue by elaninhust** [elaninhust/H5Skills#2]
客户端内嵌或者微信内部,我们都可能碰到横向滚动条隐藏的高(bian)端(tai)需求

![2081544514006_ pic_hd](https://user-images.githubusercontent.com/19330485/49785291-0c98ec80-fd5b-11e8-9ced-ad415a69e606.jpg)

### 以前普遍的做法
```css
::webkit-scrollbar {
    display: none;
}
```

### 但是

webview 内核由 UIWebView 升级到新内核 WKWebView 后，就不生效了

> 问题分析：只要添加了 -webkit-overflow-scrolling: touch 平滑滚动属性，隐藏滚动条样式就会失效。

### 新的思路

给最外层的容器添加伪类...利用伪类元素占位来遮住滚动条(亲测好使)

```css
ul::after{
    content: '';
    position: absolute;
    width: 100%;
    box-sizing: content-box;
    padding: 0 0.4rem;
    height: 0.26667rem;
    bottom: 0;
    left: 0;
    background: #f2f2f3; 
    z-index: 9999;
}
```
